"""migrate

Revision ID: 57ad1b193a42
Revises: 0b286482082b
Create Date: 2026-02-05 01:37:48.896607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ad1b193a42'
down_revision: Union[str, None] = '0b286482082b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('attachment_file_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'users', ['last_updated_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'leave_requests', 'users', ['deleted_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'leave_requests', 'users', ['created_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('users', sa.Column('attachment_file_ids', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attachment_file_ids')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'attachment_file_ids')
    # ### end Alembic commands ###
