"""migrate

Revision ID: 74fa7fa10fc6
Revises: 
Create Date: 2026-02-05 12:51:08.253496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fa7fa10fc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('time_start', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('time_end', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['deleted_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'tasks', 'users', ['last_updated_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'time_end')
    op.drop_column('tasks', 'time_start')
    op.drop_column('tasks', 'date')
    # ### end Alembic commands ###
