"""migrate

Revision ID: a9dcd1c25d7f
Revises: 
Create Date: 2026-01-12 19:45:43.287047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9dcd1c25d7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_locations', sa.Column('attendance_max_time', sa.Time(), nullable=True))
    op.create_foreign_key(None, 'safety_observations', 'users', ['created_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'safety_observations', 'users', ['last_updated_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'safety_observations', 'users', ['deleted_by_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_column('safety_observations', 'contact_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_observations', sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'safety_observations', type_='foreignkey')
    op.drop_constraint(None, 'safety_observations', type_='foreignkey')
    op.drop_constraint(None, 'safety_observations', type_='foreignkey')
    op.drop_column('attendance_locations', 'attendance_max_time')
    # ### end Alembic commands ###
